Repository madrisan/nagios-plugins-linux, pull requests merged in 2022-02, with the labels that each got.

#96 Add icinga2 command config
  contrib/README.md
  contrib/icinga2/CheckCommands.conf
Labels: first contribution

#98 Fix typo: thresholods -> thresholds
  plugins/check_network.c
Labels: bug

#101 Make sure sysfs is mounted when needed
  include/cpudesc.h
  include/sysfsparser.h
  lib/container_docker_memory.c
  lib/cpudesc.c
  lib/cputopology.c
  lib/sysfsparser.c
  plugins/check_cpu.c
  plugins/check_cpufreq.c
  plugins/check_fc.c
  plugins/check_load.c
  plugins/check_temperature.c
Labels: enhancement

#102 Add missing values
  contrib/icinga2/CheckCommands.conf
Labels: contrib

#103 workflows: update os versions used in tests
  .github/workflows/build-checks.yml
  README.md
Labels: enhancement, ci
